### ISSUE TITLE
No reliable procedure

### ISSUE THREAD

**Issue by fuuddanni** [lgandx/CCrawlDNS#1]
Hi Laurent, i like your scripting Idea, but i sometimes get an exception which isn´t handled by the programm. I tried both python 2.7 and 3.4. I also pip install simplejson, but with the same result. My requirements should be satisfied, but i don´t know, which exactly versions are preferred.

I attached you a Screenshot cause i don´t know, where the Script stucks.

Thx you for your reply and greetings
![ccrawl](https://user-images.githubusercontent.com/6312269/61909346-32fa4980-af32-11e9-9403-9d26d4a16b0e.PNG)

**Comment by fuuddanni** [comment]
Here is the running example: 
![running](https://user-images.githubusercontent.com/6312269/61910006-c5e7b380-af33-11e9-9e43-7cdc618032cb.PNG)

**Comment by lgandx** [comment]
Hey man, 

Sorry I forgot to remove a debugging except: raise.

Now fixed!

Cheers,
